name = "escolinha-api-worker"
main = "worker-api.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
account_id = "278e128913eb26e560fcd86fc067395e"

[triggers]
crons = ["*/2 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "escolinha-cache"
database_id = "79f36b06-d179-48d0-8db6-1e8f848a3beb"

[vars]
# Não coloque a MONGODB_URI aqui! 
# Use o comando: npx wrangler secret put MONGODB_URI
